radar-beta
  title Skill Radar - Dave
  axis csharp["C#"], dotnet[".NET Runtime"], aspnet["ASP.NET Core"], efcore["EF Core"], wpf["WPF"], cve["CVE Analysis"], perf["Performance"], maui[".NET MAUI"]
  curve current["Current Strengths"]{10,9,7,6,6,7,8,5}
  curve target["Growth Goals 2025"]{9,10,9,8,7,9,9,7}
  showLegend true
  max 10
  min 0
  graticule polygon
  ticks 5
