// MIT License
// Copyright (c) 2025 Dave Black
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using MermaidPad.Services.AI;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System.Diagnostics.CodeAnalysis;

namespace MermaidPad.ViewModels.Panels;

/// <summary>
/// Represents the view model for the AI panel, providing properties and commands for generating, explaining, and
/// improving diagrams using an AI service.
/// </summary>
/// <remarks>
/// This view model is designed for use in MVVM applications and exposes properties for data binding to
/// the view. It manages the state and interactions with the underlying AI service, including handling user prompts,
/// displaying results, and updating status messages. Commands are provided for generating diagrams, explaining
/// diagrams, suggesting improvements, and managing results. The view model raises the <see cref="DiagramGenerated"/>
/// event when a new diagram is ready to be inserted into the editor.
/// </remarks>
[SuppressMessage("ReSharper", "MemberCanBeMadeStatic.Global", Justification = "ViewModel properties are instance-based for binding.")]
[SuppressMessage("ReSharper", "PropertyCanBeMadeInitOnly.Global", Justification = "ViewModel properties are set during initialization by the MVVM framework.")]
[SuppressMessage("ReSharper", "MemberCanBePrivate.Global", Justification = "ViewModel properties are accessed by the view for data binding.")]
[SuppressMessage("ReSharper", "UnusedMember.Global", Justification = "ViewModel members are accessed by the view for data binding.")]
public sealed partial class AIPanelViewModel : ViewModelBase
{
    /// <summary>
    /// Provides logging capabilities for the <see cref="AIPanelViewModel"/> class.
    /// </summary>
    private readonly ILogger<AIPanelViewModel> _logger;

    /// <summary>
    /// Backing reference to the currently configured AI service implementation.
    /// </summary>
    /// <remarks>
    /// This field is assigned during construction and may be replaced via <see cref="UpdateAIService"/>.
    /// It is non-null for the lifetime of the view model after construction.
    /// </remarks>
    private IAIService _aiService;

    /// <summary>
    /// The user's natural-language prompt used to request a generated diagram from the AI service.
    /// </summary>
    /// <remarks>
    /// This property is generated by the CommunityToolkit.Mvvm <c>ObservableProperty</c> source generator.
    /// It is intended for two-way binding with the view.
    /// </remarks>
    [ObservableProperty]
    public partial string PromptText { get; set; } = string.Empty;

    /// <summary>
    /// The textual result returned from the AI service (typically Mermaid diagram code or an explanation).
    /// </summary>
    /// <remarks>
    /// This property is generated by the CommunityToolkit.Mvvm <c>ObservableProperty</c> source generator.
    /// It is intended for display in the panel and can be inserted into the editor via commands exposed by the view model.
    /// </remarks>
    [ObservableProperty]
    public partial string ResultText { get; set; } = string.Empty;

    /// <summary>
    /// Indicates whether an AI operation is currently in progress.
    /// </summary>
    /// <remarks>
    /// UI elements can bind to this property to show progress indicators and to disable input while the
    /// view model is awaiting responses from the AI service.
    /// </remarks>
    [ObservableProperty]
    public partial bool IsProcessing { get; set; }

    /// <summary>
    /// Indicates whether the currently configured AI service is ready for use (API key configured and validated).
    /// </summary>
    /// <remarks>
    /// This property reflects the <see cref="IAIService.IsConfigured"/> value of the active service.
    /// If <see langword="false"/>, commands that require a configured AI will surface guidance in <see cref="StatusMessage"/>.
    /// </remarks>
    [ObservableProperty]
    public partial bool IsConfigured { get; set; }

    /// <summary>
    /// Human-readable status or error message intended to be displayed in the UI.
    /// </summary>
    /// <remarks>
    /// Use this property to provide feedback to the user about validation, progress, errors, and successful operations.
    /// </remarks>
    [ObservableProperty]
    public partial string StatusMessage { get; set; } = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="AIPanelViewModel"/> class using application-level services.
    /// </summary>
    /// <remarks>
    /// <para>This constructor retrieves required services from the application's dependency injection
    /// container to configure the main window. It is typically used when creating the main window at application
    /// startup.</para>
    /// <para>
    /// This constructor lives specifically for the purpose of avoiding this warning:
    ///     AVLN3001: XAML resource "avares://MermaidPad/Views/Panels/AIPanel.axaml" won't be reachable via runtime loader, as no public constructor was found
    /// </para>
    /// </remarks>
    public AIPanelViewModel()
        : this(
            App.Services.GetRequiredService<ILogger<AIPanelViewModel>>(),
            App.Services.GetRequiredService<IAIService>())
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="AIPanelViewModel"/> class with the specified AI service.
    /// </summary>
    /// <param name="logger">The logger instance for this view model.</param>
    /// <param name="aiService">The AI service implementation to use for generating, explaining, and improving diagrams.</param>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="aiService"/> is <see langword="null"/>.</exception>
    public AIPanelViewModel(ILogger<AIPanelViewModel> logger, IAIService aiService)
    {
        ArgumentNullException.ThrowIfNull(aiService);

        _logger = logger;
        _aiService = aiService;
        IsConfigured = _aiService.IsConfigured;

        if (!IsConfigured)
        {
            StatusMessage = "AI is not configured. Please configure your API key in Settings.";
        }
    }

    /// <summary>
    /// Updates the AI service used by the view model, typically called when settings change at runtime.
    /// </summary>
    /// <param name="newService">The new <see cref="IAIService"/> instance to use.</param>
    /// <remarks>
    /// After calling this method the view model will reflect the new service's <see cref="IAIService.IsConfigured"/>
    /// state and update <see cref="StatusMessage"/> accordingly.
    /// </remarks>
    public void UpdateAIService(IAIService newService)
    {
        ArgumentNullException.ThrowIfNull(newService);

        _aiService = newService;
        IsConfigured = newService.IsConfigured;
        StatusMessage = !IsConfigured ? "AI is not configured. Please configure your API key in Settings." : string.Empty;
    }

    /// <summary>
    /// Command handler that generates a Mermaid diagram from the current <see cref="PromptText"/>.
    /// </summary>
    /// <remarks>
    /// This method is exposed as a command via the CommunityToolkit.Mvvm <c>RelayCommand</c> source generator.
    /// It updates <see cref="IsProcessing"/>, <see cref="StatusMessage"/>, and <see cref="ResultText"/> and raises
    /// <see cref="DiagramGenerated"/> when a diagram is produced.
    /// </remarks>
    /// <returns>A task representing the asynchronous operation.</returns>
    [RelayCommand]
    private async Task GenerateDiagramAsync()
    {
        if (!IsConfigured)
        {
            StatusMessage = "Please configure AI in Settings first.";
            return;
        }

        if (string.IsNullOrWhiteSpace(PromptText))
        {
            StatusMessage = "Please enter a description of the diagram you want to generate.";
            return;
        }

        IsProcessing = true;
        StatusMessage = "Generating diagram...";
        ResultText = string.Empty;

        try
        {
            string result = await _aiService.GenerateDiagramFromPromptAsync(PromptText);
            ResultText = result;
            StatusMessage = "Diagram generated successfully! Copy the code to the editor.";

            // Raise event to insert into editor
            OnDiagramGenerated(result);
        }
        catch (Exception ex)
        {
            StatusMessage = $"Error: {ex.Message}";
            ResultText = string.Empty;
        }
        finally
        {
            IsProcessing = false;
        }
    }

    /// <summary>
    /// Command handler that produces a human-readable explanation for the provided Mermaid code.
    /// </summary>
    /// <param name="mermaidCode">The Mermaid diagram code to explain. If <see langword="null"/> or empty, the command is no-op and updates <see cref="StatusMessage"/>.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    [RelayCommand]
    private async Task ExplainDiagramAsync(string? mermaidCode)
    {
        if (!IsConfigured)
        {
            StatusMessage = "Please configure AI in Settings first.";
            return;
        }

        if (string.IsNullOrWhiteSpace(mermaidCode))
        {
            StatusMessage = "No diagram to explain. Please create a diagram first.";
            return;
        }

        IsProcessing = true;
        StatusMessage = "Explaining diagram...";
        ResultText = string.Empty;

        try
        {
            ResultText = await _aiService.ExplainDiagramAsync(mermaidCode);
            StatusMessage = "Explanation generated successfully!";
        }
        catch (Exception ex)
        {
            StatusMessage = $"Error: {ex.Message}";
            ResultText = string.Empty;
        }
        finally
        {
            IsProcessing = false;
        }
    }

    /// <summary>
    /// Command handler that analyzes the supplied Mermaid code and returns suggestions for improvements.
    /// </summary>
    /// <param name="mermaidCode">The Mermaid diagram code to analyze. If <see langword="null"/> or empty, the command is no-op and updates <see cref="StatusMessage"/>.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    [RelayCommand]
    private async Task SuggestImprovementsAsync(string? mermaidCode)
    {
        if (!IsConfigured)
        {
            StatusMessage = "Please configure AI in Settings first.";
            return;
        }

        if (string.IsNullOrWhiteSpace(mermaidCode))
        {
            StatusMessage = "No diagram to analyze. Please create a diagram first.";
            return;
        }

        IsProcessing = true;
        StatusMessage = "Analyzing diagram...";
        ResultText = string.Empty;

        try
        {
            ResultText = await _aiService.SuggestImprovementsAsync(mermaidCode);
            StatusMessage = "Suggestions generated successfully!";
        }
        catch (Exception ex)
        {
            StatusMessage = $"Error: {ex.Message}";
            ResultText = string.Empty;
        }
        finally
        {
            IsProcessing = false;
        }
    }

    /// <summary>
    /// Command handler that inserts the current <see cref="ResultText"/> into the editor by raising <see cref="DiagramGenerated"/>
    /// </summary>
    /// <remarks>
    /// If <see cref="ResultText"/> is empty or whitespace, no event is raised.
    /// This method is exposed as a command via the CommunityToolkit.Mvvm <c>RelayCommand</c> source generator.
    /// </remarks>
    [RelayCommand]
    private void InsertResultToEditor()
    {
        if (!string.IsNullOrWhiteSpace(ResultText))
        {
            OnDiagramGenerated(ResultText);
        }
    }

    /// <summary>
    /// Command handler that clears the prompt, result, and status fields.
    /// </summary>
    /// <remarks>
    /// This method is exposed as a command via the CommunityToolkit.Mvvm <c>RelayCommand</c> source generator.
    /// Use this to reset the panel to its initial state.
    /// </remarks>
    [RelayCommand]
    private void ClearResult()
    {
        ResultText = string.Empty;
        PromptText = string.Empty;
        StatusMessage = string.Empty;
    }

    /// <summary>
    /// Event raised when a diagram is generated and should be inserted into the editor.
    /// </summary>
    /// <remarks>
    /// Subscribers may insert the provided Mermaid diagram text into the editor. The event is invoked on the caller's
    /// synchronization context (typically the UI thread) because it is raised from command handlers that run on the UI thread.
    /// </remarks>
    public event EventHandler<string>? DiagramGenerated;

    /// <summary>
    /// Raises the <see cref="DiagramGenerated"/> event with the supplied diagram text.
    /// </summary>
    /// <param name="diagram">The Mermaid diagram text to provide to event subscribers.</param>
    private void OnDiagramGenerated(string diagram)
    {
        DiagramGenerated?.Invoke(this, diagram);
    }
}
