# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build and Release

on:
  push:
    tags:
      - 'v*'            # Triggers on version tags like v1.0.0
  workflow_dispatch:    # Allows manual triggering
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string
      is_preview:
        description: 'Mark this release as a preview (pre-release)?'
        required: false
        default: false
        type: boolean

jobs:
  restrict-user:
    runs-on: ubuntu-latest
    steps:
      - name: Restrict to allowed user
        run: |
          if [ "${{ github.actor }}" != "udlose" ]; then
            echo "Only udlose can run this workflow."
            exit 1
          fi

  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Extract version
        id: version
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/v* ]]; then
            # Tag push: extract from tag
            VERSION=${GITHUB_REF#refs/tags/v}
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Manual run: use input
            VERSION="${{ github.event.inputs.version }}"
          else
            # Fallback
            VERSION="dev-$(date +'%Y%m%d-%H%M%S')"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

  # Build matrix for all platforms
  build:
    name: Build (${{ matrix.name }})
    needs: [restrict-user, get-version]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Windows x64
            os: windows-latest
            rid: win-x64
            extension: .exe
          - name: Windows ARM64
            os: windows-latest
            rid: win-arm64
            extension: .exe
          - name: Linux x64
            os: ubuntu-latest
            rid: linux-x64
            extension: ''
          - name: Linux ARM64
            os: ubuntu-latest
            rid: linux-arm64
            extension: ''
          - name: macOS x64
            os: macos-latest
            rid: osx-x64
            extension: ''
          - name: macOS ARM64
            os: macos-latest
            rid: osx-arm64
            extension: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore MermaidPad.csproj

      - name: Publish
        run: dotnet publish MermaidPad.csproj -c Release -r ${{ matrix.rid }} -o ./publish -p:Version=${{ needs.get-version.outputs.version }} -p:AssemblyVersion=${{ needs.get-version.outputs.version }} -p:FileVersion=${{ needs.get-version.outputs.version }}
      
      # Add ad-hoc code signing for macOS binaries
      - name: Ad-hoc Sign macOS Binary
        if: matrix.rid == 'osx-x64' || matrix.rid == 'osx-arm64'
        shell: bash
        working-directory: ./publish
        run: |
          BIN_NAME="MermaidPad${{ matrix.extension }}"
          echo "Ad-hoc signing macOS binary: $BIN_NAME"
          
          # Ad-hoc sign the main executable
          codesign --force --sign - "$BIN_NAME"
          
          # Verify the signing worked
          codesign --verify --verbose "$BIN_NAME"
          echo "Success: Ad-hoc signing completed for $BIN_NAME"
          
          # Also sign any .dylib files if they exist
          if ls *.dylib 1> /dev/null 2>&1; then
            echo "Found .dylib files, signing them too..."
            for dylib in *.dylib; do
              echo "Signing: $dylib"
              codesign --force --sign - "$dylib"
              codesign --verify --verbose "$dylib"
            done
          fi
          
          # Clear any quarantine attributes that might have been set
          xattr -cr . || echo "No quarantine attributes to clear"
          
          echo "Success: All macOS binaries have been ad-hoc signed"

      - name: Prepare artifact
        shell: bash
        working-directory: ./publish
        run: |
          ZIP_NAME="MermaidPad-${{ needs.get-version.outputs.version }}-${{ matrix.rid }}.zip"
          BIN_NAME="MermaidPad${{ matrix.extension }}"
          if [ "${{ matrix.extension }}" != ".exe" ]; then
            chmod +x "$BIN_NAME"
            zip -r "$ZIP_NAME" ./*
          else
            powershell.exe -Command "Compress-Archive -Path * -DestinationPath $ZIP_NAME"
          fi
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ./publish/${{ env.ZIP_NAME }}
          if-no-files-found: error

  # Create GitHub release
  release:
    name: Create Release
    needs: [restrict-user, get-version, build]
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.version != '')
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create or update tag for manual runs
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f v${{ needs.get-version.outputs.version }}
          git push origin v${{ needs.get-version.outputs.version }} --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.get-version.outputs.version }}
          name: MermaidPad v${{ needs.get-version.outputs.version }}
          artifacts: "./artifacts/**/*"
          generateReleaseNotes: true
          allowUpdates: true
          prerelease: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.is_preview == 'true' }}
          body: |
            ## MermaidPad v${{ needs.get-version.outputs.version }}

            ### Requirements
            - .NET 9 Runtime ([Download here](https://dotnet.microsoft.com/download/dotnet/9.0))
            - Windows: WebView2 Runtime ([Download here](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download))
            - Linux: libwebkit2gtk-4.0-37+ (for WebKit support)
            - macOS: WebKit (included on macOS by default - [Download](https://webkit.org/downloads/))

            ### macOS Installation Notes
            **Important**: macOS binaries are ad-hoc signed. On first launch:
            1. Right-click the app -> **"Open"** (not double-click)
            2. Click **"Open"** when prompted about unidentified developer
            3. OR via terminal: `xattr -cr MermaidPad-*-osx-* && ./MermaidPad-*-osx-*`

            ### Downloads
            Choose the appropriate version for your platform:

            - #### Windows:
              - `x64`: `MermaidPad-${{ needs.get-version.outputs.version }}-win-x64.exe`
              - `arm64`: `MermaidPad-${{ needs.get-version.outputs.version }}-win-arm64.exe`

            - #### Linux:
              - `x64`: `MermaidPad-${{ needs.get-version.outputs.version }}-linux-x64`
              - `arm64`: `MermaidPad-${{ needs.get-version.outputs.version }}-linux-arm64`

            - #### MacOS:
  
              Not sure which one?
              If you have an:
              - Apple M1/M2/M3 = Apple Silicon `arm64`
              - Intel = Intel Mac `x64`

              Both architectures are supported on MacOS, but you should choose download for your native CPU Architecture:
              - Intel (`x64`): `MermaidPad-${{ needs.get-version.outputs.version }}-osx-x64`
              - Apple Silicon (`arm64`): `MermaidPad-${{ needs.get-version.outputs.version }}-osx-arm64`

            ### Installation
            1. Download the appropriate file for your platform
            2. Make executable (Linux/macOS): `chmod +x MermaidPad-*`
            3. Run directly: `./MermaidPad-*` or double-click (on Windows)

  bundle-macos-app:
    name: Bundle macOS .app
    needs: [restrict-user, get-version, build]
    strategy:
      matrix:
        include:
          - rid: osx-x64
          - rid: osx-arm64
    uses: ./.github/workflows/macos-bundle.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
      rid: ${{ matrix.rid }}
    permissions:
      contents: write
