name: Release on Merge

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    name: Build and Package (${{ matrix.rid }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - rid: win-x64
            runner: windows-latest
          - rid: win-arm64
            runner: windows-latest
          - rid: linux-x64
            runner: ubuntu-latest
          - rid: linux-arm64
            runner: ubuntu-latest
          - rid: osx-x64
            runner: macos-latest
          - rid: osx-arm64
            runner: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      # Extracts <Version> from Directory.Build.props and exposes it as an output
      - name: Get version from Directory.Build.props
        id: version
        shell: bash
        run: |
          version=$(grep -oP '(?<=<Version>).*?(?=</Version>)' Directory.Build.props | head -n 1)
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Publish self-contained (${{ matrix.rid }})
        run: >
          dotnet publish
          -c Release
          -r ${{ matrix.rid }}
          --self-contained true
          -p:PublishSingleFile=true
          -o publish

      - name: Package artifact
        shell: bash
        run: |
          ARTIFACT="MermaidPad-${{ env.VERSION }}-${{ matrix.rid }}"
          if [[ "${{ matrix.runner }}" == "windows-latest" ]]; then
            7z a "$ARTIFACT.zip" ./publish/*
          else
            tar -czf "$ARTIFACT.tar.gz" -C publish .
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MermaidPad-${{ env.VERSION }}-${{ matrix.rid }}
          path: |
            MermaidPad-${{ env.VERSION }}-${{ matrix.rid }}.*

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-and-package
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # Get the version from any artifact's version (they're all the same)
      - name: Extract version from artifact name
        id: get_version
        run: |
          echo "version=${{ needs.build-and-package.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          name: MermaidPad v${{ steps.extract_version.outputs.version }}
          body: |
            Automated cross-platform release for MermaidPad v${{ steps.extract_version.outputs.version }}
          files: artifacts/**/*
